# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付款'),
        ),
    ]
