# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190219_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已评价'), (6, '已取消')], default=1, verbose_name='订单状态'),
        ),
    ]
