# 邮箱验证链接有效时间
VERIFY_EMAIL_TOKEN_EXPIRES = 7200

# 用户地址数量达到上线
USER_ADDRESS_COUNTS_LIMIT = 20

# 用户浏览记录保存数量
USER_BROWSING_HISTORY_COUNTS_LIMIT = 5


# 短信验证码redis存储有效时间:s
SMS_CODE_REDIS_EXPIRES = 300

# 发送短信模板
SEND_SMS_TEMP_ID = 1

# 短信发送时间间隔
SEND_SMS_CODE_INTERVAL = 60